version: 2
jobs:
  build:
    docker:
      - image: docker:19.03-rc-git
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -f dotnetcore2.2-sonar.dockerfile -t bockyang/dotnet-core:sdk2.2-sonar .
            docker build -f dotnetcore3.0-sonar.dockerfile -t bockyang/dotnet-core:sdk3.0-sonar .
      - run:
          name: Push  to DockerHub
          command: |
            echo "To be implemented"
      
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master