version: 2
jobs:
  build:
    docker:
      - image: docker:19.03-rc-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -f dotnetcore2.2-sonar.dockerfile -t tinyworks/dotnet-core:sdk2.2-sonar .
            docker build -f dotnetcore3.0-sonar.dockerfile -t tinyworks/dotnet-core:sdk3.0-sonar .
            docker build -f dotnetcore3.1-sonar.dockerfile -t tinyworks/dotnet-core:sdk3.1-sonar .
            docker build -f dotnetcore3.1-mono.dockerfile -t tinyworks/dotnet-core:sdk3.1-mono .
            docker build -f gcloud270.0.0-newman.dockerfile -t tinyworks/gcloud-sdk:270.0.0-newman-alpine .
      - run:
          name: Push to DockerHub
          command: |
            echo $DOCKER_USER
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker push tinyworks/dotnet-core
            docker push tinyworks/gcloud-sdk

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master